OLED_DRIVER_ENABLE  = no
OLED_ENABLE = no
OLED_TIMEOUT = 0
OLED_DRIVER = SSD1306

RGBLIGHT_ENABLE = no
LEADER_ENABLE = yes

LTO_ENABLE = no


POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = cirque_pinnacle_i2c
MOUSEKEY_ENABLE = yes